apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular
  namespace: angular
spec:
  rules:
  - host: "app.mhasnain.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service1
            port:
              number: 80
  