apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 2m0s
  secretRef: 
    name: mysecret
  url: https://github.com/hasnain28/minikube
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 2m0s 
  prune: true
  path: "./cluster"
  sourceRef:
    kind: GitRepository
    name: flux-system
  